# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0002_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='tipo',
            field=models.CharField(choices=[('Econ\xf3mico', 'Econ\xf3mico'), ('Especial', 'Especial')], max_length=50),
        ),
    ]
