# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usr/')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('curp', models.CharField(max_length=18)),
                ('rfc', models.CharField(max_length=18)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=70)),
                ('calle', models.CharField(max_length=40)),
                ('numero_interior', models.IntegerField(blank=True, null=True)),
                ('numero_exterior', models.IntegerField(blank=True, null=True)),
                ('colonia', models.CharField(max_length=40)),
                ('codigo_postal', models.IntegerField()),
                ('pais', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('municipio', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=13)),
                ('celular', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('datos_adicionales', models.TextField(blank=True, null=True)),
                ('id_persona', models.CharField(max_length=13)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.IntegerField(default=1, editable=False)),
                ('cargo', models.CharField(max_length=75)),
                ('areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
            ],
        ),
    ]
