# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20171031_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
