# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20171031_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='motivo_baja',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='observaciones',
        ),
    ]
