# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20171031_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=40),
        ),
    ]
