# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20171031_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='motivo_baja',
            field=models.CharField(blank=True, choices=[('Renuncia', 'Renuncia'), ('Despido', 'Despido'), ('Jubilaci\xf3n', 'Jubilacion')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=70),
        ),
    ]
