# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20171105_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=70),
        ),
    ]
